AUGMENTATION: True

IMAGE_SIZE: [224, 224, 3]   # VGG16 input size

BATCH_SIZE: 8

INCLUDE_TOP: False

EPOCHS: 1                

CLASSES: 3                 # Healthy, Coccidiosis, Salmonella

WEIGHTS: imagenet

LEARNING_RATE: 0.001
